[profile.default]
src = "src"
out = "out"
libs = ["lib"]

optimizer = true
optimizer_runs = 200

remappings = [
    'forge-std/=lib/forge-std/src/',
    '@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/',
    '@flarenetwork/flare-periphery-contracts/=node_modules/@flarenetwork/flare-periphery-contracts/',
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
